### ISSUE TITLE
Support for proc_macro_attribute

### ISSUE THREAD

**Issue by jvdwrf** [snowfoxsh/nestify#10]
I think this library would work better as a proc_macro_attribute, since it reduces the amount of nesting code.
Would you see this as a feasable alternative to the current implementation?

**Comment by snowfoxsh** [comment]
Unfortunate it cannot be used with attribute. When attributes are used rust first validates that the grammar is valid rust code. Since nestify offers an extension of the rust syntax it will not compile. Regular macro_rules! style macros are able to accept arbitrary syntax. However, if there is a way to get around this limitation then I would love to implement it.
